[
  {
    DatabaseId: 1,
    CardId: 101,
    CardName: "Dragon Warrior",
    CardPicture: "dragon_warrior.png",
    Health: 1200,
    Defense: 800,
    Attack: 1500,
    Affiliation: "Dragon Clan",
    Origin: "Ancient Mountains",
    AttackSpeed: 50,
    Skills: "Fire Breath, Claw Slash",
    Era: "Medieval",
    SpecialAbilities: "Flying, Fire Immunity",
    CardRecovery: 300,
    Abilities: "Roar, Intimidate",
    Constraints: "Water Weakness",
    BuffDebuff: "Burn, Fear",
    Energy: "100",
    Species: "Dragon",
    Resistances: "Fire, Earth",
    MagicType: "Fire",
    PhysicalType: "Melee",
    Crit: "20%",
    Charisma: "80",
    Cost: 250.0,
    CardType: "Rare",
    Owned: true,
  },
  {
    DatabaseId: 2,
    CardId: 102,
    CardName: "Elf Archer",
    CardPicture: "elf_archer.png",
    Health: 900,
    Defense: 600,
    Attack: 700,
    Affiliation: "Elven Kingdom",
    Origin: "Enchanted Forest",
    AttackSpeed: 70,
    Skills: "Arrow Storm, Stealth",
    Era: "Medieval",
    SpecialAbilities: "Eagle Eye, Silent Step",
    CardRecovery: 250,
    Abilities: "Agility, Precision",
    Constraints: "Close Combat Weakness",
    BuffDebuff: "Focus, Speed",
    Energy: "80",
    Species: "Elf",
    Resistances: "Wind, Light",
    MagicType: "Nature",
    PhysicalType: "Ranged",
    Crit: "25%",
    Charisma: "60",
    Cost: 180.0,
    CardType: "Uncommon",
    Owned: false,
  },
  {
    DatabaseId: 3,
    CardId: 103,
    CardName: "Dark Sorcerer",
    CardPicture: "dark_sorcerer.png",
    Health: 700,
    Defense: 500,
    Attack: 1300,
    Affiliation: "Shadow Order",
    Origin: "Cursed Lands",
    AttackSpeed: 40,
    Skills: "Dark Magic, Curse",
    Era: "Ancient",
    SpecialAbilities: "Necromancy, Shadow Walk",
    CardRecovery: 200,
    Abilities: "Spell Casting, Dark Arts",
    Constraints: "Light Weakness",
    BuffDebuff: "Curse, Fear",
    Energy: "120",
    Species: "Human",
    Resistances: "Dark, Poison",
    MagicType: "Dark",
    PhysicalType: "Magic",
    Crit: "15%",
    Charisma: "70",
    Cost: 220.0,
    CardType: "Epic",
    Owned: true,
  },
  {
    DatabaseId: 4,
    CardId: 104,
    CardName: "Giant Troll",
    CardPicture: "giant_troll.png",
    Health: 2000,
    Defense: 1500,
    Attack: 900,
    Affiliation: "Troll Tribe",
    Origin: "Mountain Caves",
    AttackSpeed: 20,
    Skills: "Regeneration, Smash",
    Era: "Ancient",
    SpecialAbilities: "Regeneration, Stone Skin",
    CardRecovery: 500,
    Abilities: "Strength, Endurance",
    Constraints: "Fire Weakness",
    BuffDebuff: "Rage, Slowness",
    Energy: "150",
    Species: "Troll",
    Resistances: "Earth, Physical",
    MagicType: "Earth",
    PhysicalType: "Melee",
    Crit: "10%",
    Charisma: "30",
    Cost: 300.0,
    CardType: "Legendary",
    Owned: false,
  },
  {
    DatabaseId: 5,
    CardId: 105,
    CardName: "Knight Paladin",
    CardPicture: "knight_paladin.png",
    Health: 1100,
    Defense: 900,
    Attack: 1000,
    Affiliation: "Royal Guard",
    Origin: "Kingdom of Light",
    AttackSpeed: 60,
    Skills: "Shield Block, Sword Slash",
    Era: "Medieval",
    SpecialAbilities: "Holy Light, Protection",
    CardRecovery: 350,
    Abilities: "Leadership, Valor",
    Constraints: "Darkness Weakness",
    BuffDebuff: "Inspire, Courage",
    Energy: "90",
    Species: "Human",
    Resistances: "Light, Holy",
    MagicType: "Holy",
    PhysicalType: "Melee",
    Crit: "18%",
    Charisma: "85",
    Cost: 200.0,
    CardType: "Rare",
    Owned: true,
  },
  {
    DatabaseId: 6,
    CardId: 106,
    CardName: "Necromancer",
    CardPicture: "necromancer.png",
    Health: 800,
    Defense: 600,
    Attack: 1200,
    Affiliation: "Undead Legion",
    Origin: "Haunted Marshes",
    AttackSpeed: 50,
    Skills: "Raise Dead, Dark Pact",
    Era: "Ancient",
    SpecialAbilities: "Undead Control, Life Drain",
    CardRecovery: 300,
    Abilities: "Dark Rituals, Necromancy",
    Constraints: "Holy Weakness",
    BuffDebuff: "Decay, Fear",
    Energy: "110",
    Species: "Human",
    Resistances: "Dark, Poison",
    MagicType: "Dark",
    PhysicalType: "Magic",
    Crit: "22%",
    Charisma: "50",
    Cost: 210.0,
    CardType: "Epic",
    Owned: false,
  },
  {
    DatabaseId: 7,
    CardId: 107,
    CardName: "Fairy Mage",
    CardPicture: "fairy_mage.png",
    Health: 600,
    Defense: 400,
    Attack: 1100,
    Affiliation: "Fairy Circle",
    Origin: "Enchanted Grove",
    AttackSpeed: 80,
    Skills: "Magic Burst, Healing Light",
    Era: "Mythical",
    SpecialAbilities: "Flight, Magic Resistance",
    CardRecovery: 200,
    Abilities: "Magic Affinity, Healing",
    Constraints: "Physical Weakness",
    BuffDebuff: "Blessing, Speed",
    Energy: "70",
    Species: "Fairy",
    Resistances: "Magic, Light",
    MagicType: "Nature",
    PhysicalType: "Magic",
    Crit: "30%",
    Charisma: "90",
    Cost: 190.0,
    CardType: "Rare",
    Owned: true,
  },
  {
    DatabaseId: 8,
    CardId: 108,
    CardName: "Dwarf Warrior",
    CardPicture: "dwarf_warrior.png",
    Health: 1300,
    Defense: 1000,
    Attack: 800,
    Affiliation: "Dwarven Kingdom",
    Origin: "Mountain Halls",
    AttackSpeed: 40,
    Skills: "Axe Swing, Shield Bash",
    Era: "Medieval",
    SpecialAbilities: "Sturdy, Stone Skin",
    CardRecovery: 400,
    Abilities: "Strength, Endurance",
    Constraints: "Magic Weakness",
    BuffDebuff: "Fortitude, Rage",
    Energy: "120",
    Species: "Dwarf",
    Resistances: "Earth, Physical",
    MagicType: "Earth",
    PhysicalType: "Melee",
    Crit: "15%",
    Charisma: "40",
    Cost: 230.0,
    CardType: "Uncommon",
    Owned: false,
  },
  {
    DatabaseId: 9,
    CardId: 109,
    CardName: "Orc Berserker",
    CardPicture: "orc_berserker.png",
    Health: 1400,
    Defense: 700,
    Attack: 1300,
    Affiliation: "Orc Horde",
    Origin: "Savage Plains",
    AttackSpeed: 30,
    Skills: "Berserk, War Cry",
    Era: "Ancient",
    SpecialAbilities: "Rage, Bloodlust",
    CardRecovery: 450,
    Abilities: "Strength, Ferocity",
    Constraints: "Mind Weakness",
    BuffDebuff: "Rage, Weakness",
    Energy: "130",
    Species: "Orc",
    Resistances: "Physical, Earth",
    MagicType: "None",
    PhysicalType: "Melee",
    Crit: "25%",
    Charisma: "35",
    Cost: 210.0,
    CardType: "Epic",
    Owned: true,
  },
  {
    DatabaseId: 10,
    CardId: 110,
    CardName: "Vampire Lord",
    CardPicture: "vampire_lord.png",
    Health: 1100,
    Defense: 800,
    Attack: 1500,
    Affiliation: "Vampire Coven",
    Origin: "Dark Castle",
    AttackSpeed: 60,
    Skills: "Blood Drain, Bat Swarm",
    Era: "Gothic",
    SpecialAbilities: "Immortality, Hypnosis",
    CardRecovery: 350,
    Abilities: "Charm, Darkness Control",
    Constraints: "Sunlight Weakness",
    BuffDebuff: "Fear, Weakness",
    Energy: "100",
    Species: "Vampire",
    Resistances: "Dark, Poison",
    MagicType: "Dark",
    PhysicalType: "Magic",
    Crit: "20%",
    Charisma: "95",
    Cost: 250.0,
    CardType: "Legendary",
    Owned: false,
  },
];
